# Generated by Django 3.2.8 on 2022-05-04 01:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=2048)),
                ('posted_by_user_id', models.IntegerField(null=True)),
                ('posted_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
                ('post_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('body', models.CharField(max_length=2048)),
                ('posted_by_user_id', models.IntegerField(null=True)),
                ('posted_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
                ('subreddit_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1024)),
                ('mod_user_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('subreddit_id', models.IntegerField(null=True)),
            ],
        ),
    ]
