version: "3"
services:
        cs4610-final-frontend:
            stdin_open: true
            tty: true
            build:
               context: .
               dockerfile: Dockerfile
            container_name: cs4610-final-frontend
            hostname: cs4610-final-frontend
            env_file: .env
            restart: on-failure
            ports:
                - 80:80